version: '3.7'

services:
  backend:
    container_name: talking-assistant-backend-container
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - .env.staging

  frontend:
    container_name: talking-assistant-stag-frontend-container
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./frontend/src:/usr/src/app/src

