version: '3.7'

services:
  backend:
    container_name: talking-assistant-local-backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "7070:7000"
    env_file:
      - .env.development

  frontend-react:
    container_name: talking-assistant-frontend-container
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    ports:
      - "8001:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_HOST=0.0.0.0
